In [1]:
from myosuite.utils import gym as myo_gym
from config import Config
import numpy as np

MyoSuite:> Registering Myo Envs


Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/home/ubuntu/myochallenge_2025eval/.venv/lib/python3.11/site-packages/gymnasium/envs/registration.py:694: UserWarning: WARN: Overriding environment myoArmReachFixed-v0 already in registry.
  logger.warn(f"Overriding environment {new_spec.id} already in registry.")
/home/ubuntu/myochallenge_2025eval/.venv/lib/python3.11/site-packages/gymnasium/envs/registration.py:694: UserWarning: WARN: Overriding environment myoSarcArmReachFixed-v0 already in registry.
  logger.warn(f"Overriding environment {ne

In [2]:
cfg = Config()

# 1. Create environment
env = myo_gym.make(cfg.env_id)

# 2. Reset environment (returns array, not dict)
obs, info = env.reset()

print("RAW obs returned by reset():")
print(type(obs), obs.shape)

/home/ubuntu/myochallenge_2025eval/.venv/lib/python3.11/site-packages/glfw/__init__.py:917: GLFWError: (65550) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)


    MyoSuite: A contact-rich simulation suite for musculoskeletal motor control
        Vittorio Caggiano, Huawei Wang, Guillaume Durandau, Massimo Sartori, Vikash Kumar
        L4DC-2019 | https://sites.google.com/view/myosuite
    
RAW obs returned by reset():
<class 'numpy.ndarray'> (417,)


In [4]:
# 3. Get the TRUE dict-based observation
if hasattr(env, "obs_dict"):
    obs_dict = env.obs_dict
    print("\nOBS_DICT KEYS:")
    for k, v in obs_dict.items():
        print(f"{k:20s} shape={np.array(v).shape}")
        print(v)
else:
    print("ERROR: env.obs_dict not found")



OBS_DICT KEYS:
time                 shape=(1,)
[0.]
pelvis_pos           shape=(3,)
[ 2.0205e+00 -6.6971e-04  9.5000e-01]
body_qpos            shape=(58,)
[-0.4205  0.      0.      0.      0.      0.      0.      0.      0.
  0.      0.     -0.0972  0.      0.      0.      0.      0.      0.
  0.      0.      0.      0.      0.      0.      0.      0.      0.
  0.      0.      0.1368  0.1484  0.7069 -0.7405 -0.3432  0.8055 -0.1028
 -0.0829 -0.7304  0.0632  0.7     0.075  -0.2967  0.7227 -0.1361  0.2671
  0.3535  0.6598 -0.1518  0.4242  0.5184  0.919  -0.2094  0.2592  0.5106
  0.7934 -0.2042  0.2278  0.    ]
body_qvel            shape=(58,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ball_pos             shape=(3,)
[-0.8199 -0.3532  1.4178]
ball_vel             shape=(3,)
[ 5.4767  1.0182 -0.0566]
paddle_pos           shape=(3,)
[1.91   0.6677 1.2373]
pa

/home/ubuntu/myochallenge_2025eval/.venv/lib/python3.11/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.obs_dict to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.obs_dict` for environment variables or `env.get_wrapper_attr('obs_dict')` that will search the reminding wrappers.
  logger.warn(
